name: Build JAR

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build JAR
        run: sed -i "s/VERSIONPLACE/$(cat VERSION)/g" pom.xml && mvn package
      - name: Commit jar
        run: |
          mkdir -p packaged; mv target/*.jar ./packaged/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./packaged
          git commit -m "Automated creation of .jar file"
          git push